version: 0.2
env:
  secrets-manager:
    TOKEN: firstSecret:tokenForSonar
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - echo "TOKEN length ${#TOKEN}"
      - mvn verify sonar:sonar -Dsonar.projectKey=gibbsorganization -Dsonar.organization=gibbsorganization -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN 