version: 0.2
env:
    secrets-manager:
      TOKEN: firstSecret:tokenForSonar
      SNYK_TOKEN: firstSecret:tokenForSnyk
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=gibbsorganization -Dsonar.organization=gibbsorganization -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN 
      - sleep 5
      - |- 
        quality_status=$(curl -s -u $TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=gibbsorganization | jq -r '.projectStatus.status')
        echo "SonarCloud analysistatus is $quality_status"; 
        if [ $quality_status = "ERROR" ] ; then exit 1;fi
      - |-
        apt-get update
        apt-get -y install maven
        mvn snyk:test fn
      - |-
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.1/ZAP_2.16.1_Linux.tar.gz
        mkdir zap
        tar -xvf ZAP_2.16.1_Linux.tar.gz
        cd ZAP_2.16.1
        ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html
artifacts:
  files:
    - zap_report.html